FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
COPY torch-2.6.0+cpu-cp312-cp312-linux_x86_64.whl .

RUN pip install --no-cache-dir ./torch-2.6.0+cpu-cp312-cp312-linux_x86_64.whl

RUN pip install --no-cache-dir -r requirements.txt \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --timeout 300

COPY hf_cache /root/.cache/huggingface/hub

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]